name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate pacman graph
        uses: AbhishekGautam2000/pacman-contribution-graph@master
        with:
          github_user_name: josswinaya
          output_branch: pacman-output

      - name: Push Pacman SVG to pacman-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: pacman-output
          build_dir: pacman-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}